jcli admin projects create
Byzanteam/jcli pull request #2
Opened 2023-10-20 07:36 UTC by CptBreeza

2023-10-20 07:37 UTC, CptBreeza commented
先看一下整体的骨架和一些风格上的问题嘛

2023-10-20 08:00 UTC, moonRider requested changes

2023-10-20 08:00 UTC, moonRider commented on src/api/jet.ts
> +export interface createProjectArgs {
类型一般还是用的大驼峰命名吧

2023-10-20 08:00 UTC, moonRider commented on src/api/jet/mod.ts
> +async function query(query: string, variables: object, config: JetConfig) {
通用的 query 不确定类型可以通过范型指定类型
```
async function query<T>(args): Promise<T> {
  // body
}
```
使用时
```
await query<CreateProjectMutationResponse>(...)
```

2023-10-20 08:00 UTC, moonRider commented on test/api/jet.ts
> +  getProject(query: ProjectQuery): ProjectObject | undefined;
```suggestion
  getProject?(query: ProjectQuery): ProjectObject;
```

2023-10-20 08:01 UTC, moonRider commented on src/api/jet.ts
> +  createProject: (args: createProjectArgs) => Promise<Project>;
```suggestion
  createProject(args: createProjectArgs): Promise<Project>;
```

2023-10-20 08:09 UTC, CptBreeza commented on src/api/jet.ts
> +export interface createProjectArgs {
好的，我改一下

2023-10-20 08:09 UTC, CptBreeza commented on src/api/jet/mod.ts
> +async function query(query: string, variables: object, config: JetConfig) {
好的，我改一下

2023-10-20 08:09 UTC, CptBreeza commented on src/api/jet.ts
> +  createProject: (args: createProjectArgs) => Promise<Project>;
好的，我改一下

2023-10-20 08:10 UTC, CptBreeza commented on test/api/jet.ts
> +  getProject(query: ProjectQuery): ProjectObject | undefined;
这里我想要的是，`getProject` 这个函数返回一个 `ProjectObject` 或者 `undefined`。你给的写法是 `getProject` 这个 key 可有可无，应该不是一个意思吧

2023-10-20 08:24 UTC, vanppo commented on src/api/fs.ts
不能直接用 Deno.mkdir 么

2023-10-20 08:26 UTC, CptBreeza commented on src/api/fs.ts
生产环境是直接用的，测试环境做了一个 mock

2023-10-23 01:40 UTC, fahchen commented on src/api/jet.ts
> +    if (undefined === config) {
这些操作的过程留点 log 呢

2023-10-23 01:40 UTC, fahchen commented on src/api/jet/config.ts
> +  const homePath = Deno.env.get("HOME");
这个是不是也不和 deno 耦合，放到 fs 中

2023-10-23 01:40 UTC, fahchen commented on test/subcommands/admin/projects/create/action_test.ts
每一个测试用例类似于 ExUnit 的 temp_dir 那个 tag 的作用，测试完了清理一下创建的文件夹呢

2023-10-23 02:17 UTC, CptBreeza commented on src/api/jet.ts
> +    if (undefined === config) {
好的

2023-10-23 02:17 UTC, CptBreeza commented on src/api/jet/config.ts
> +  const homePath = Deno.env.get("HOME");
可以的

2023-10-23 02:17 UTC, CptBreeza commented on test/subcommands/admin/projects/create/action_test.ts
目前这个测试文件里，所有 api client 都是隔离开的

2023-10-24 00:18 UTC, fahchen commented on test/subcommands/admin/projects/create/action_test.ts
清理现场（测试的时候建的文件）是不是没做啊

2023-10-24 05:27 UTC, CptBreeza commented on test/subcommands/admin/projects/create/action_test.ts
现在都是 mock 的嘛。创建文件实际上是在 api.fs 里面的一个 Map 里写入了一项。每个用例都用了一个独立的 api 对象，它们之间是不共享数据的

2023-10-26 07:55 UTC, moonRider requested changes

2023-10-26 07:55 UTC, moonRider commented on src/api/fs.ts
> +  mkdir(path: string): Promise<void>;
```suggestion
  mkdir: typeof Deno.mkdir
```
现在的类型和 deno 的有点差异

2023-10-26 07:55 UTC, moonRider commented on src/api/jet.ts
> +      logger.debug(`Request finished in ${endInstant - startInstant}ms.`);
这个 message 需不需要表达 createProject 这个行为啊？

2023-10-26 07:55 UTC, moonRider commented on src/api/jet/mod.ts
> +  const response = await query<CreateProjectMutationResponse>(
```suggestion
  const { createProject: { project: { uuid, name, title }} } = await query<CreateProjectMutationResponse>(
```

2023-10-26 07:55 UTC, moonRider commented on src/api/jet/mod.ts
> +    title: response.createProject.project.title,
```suggestion
    id: uuid,
    name,
    title,
```

2023-10-26 07:55 UTC, moonRider commented on src/api/jet/mod.ts
> +    title: response.createProject.project.title,
前端写的时候这样会比较舒服，不知道 deno 里面需不需要这个

2023-10-26 07:55 UTC, moonRider commented on src/jcli/config/config.ts
> +  };
```suggestion
  async get() {
    if (undefined === this.#data) {
      const data = await this._fs.readTextFile(this.#path);
      const deserializedData = await this.#serializer.deserialize(data);
      this.#data = deserializedData;
    }

    return this.#data;
  };
```

2023-10-26 07:55 UTC, moonRider commented on src/jcli/config/project-json.ts
> +  toJSON = () => {
```suggestion
  toJSON() {
```

2023-10-26 07:55 UTC, moonRider commented on test/api/fs.ts
> +  }
这两个都提供了，感觉 content 应该可以直接定义为 public 的属性吧？

2023-10-26 07:57 UTC, moonRider commented on src/jcli/config/config.ts
> +  };
class 里面通常不使用箭头函数

2023-10-26 08:06 UTC, CptBreeza commented on src/api/fs.ts
> +  mkdir(path: string): Promise<void>;
这个是不要求正好是 Deno 的类型的，因为只用到了它类型的一部分，并且在测试环境里面也只 mock 这些类型的行为

2023-10-26 08:07 UTC, CptBreeza commented on src/api/jet.ts
> +      logger.debug(`Request finished in ${endInstant - startInstant}ms.`);
上面的一条日志提供了正在请求 createProject 嘛，这里是紧跟着的一条，而且这里是单线程执行，应该是能看出来是在进行哪个动作的

2023-10-26 08:07 UTC, CptBreeza commented on src/api/jet/mod.ts
> +    title: response.createProject.project.title,
可以的，我改一下

2023-10-26 08:10 UTC, CptBreeza commented on src/jcli/config/config.ts
> +  };
我看教程是，如果用你这种写法的话，会有丢失 this 的问题？https://zh.javascript.info/class#shi-yong-lei-zi-duan-zhi-zuo-bang-ding-fang-fa

2023-10-26 08:11 UTC, CptBreeza commented on test/api/fs.ts
> +  }
好的，我改一下

2023-10-26 10:02 UTC, vanppo commented on main.ts
> +import { default as adminCommand } from "@/subcommands/admin/mod.ts";
可以在 `@/subcommands/admin/mod.ts` 使用命名导出 这里就不用重命名了
```suggestion
import { adminCommand } from "@/subcommands/admin/mod.ts";
```
或者使用默认导入的方式也可以这样
```suggestion
import adminCommand from "@/subcommands/admin/mod.ts";
```

2023-10-26 10:02 UTC, vanppo commented on src/api/jet/mod.ts
> +  return resolveResponse(body);
这里是不是应该把范型参数传到下面去呀
```suggestion
  return resolveResponse<T>(body);
```

2023-10-26 11:04 UTC, moonRider approved these changes

2023-10-26 11:13 UTC, moonRider commented on src/jcli/config/config.ts
> +  };
<img width="502" alt="image" src="https://github.com/Byzanteam/jcli/assets/6049820/cf96f184-31a3-4680-8bd7-b33a1e9f088a">
如果有多个实例的话这样会极大的消耗内存。this 丢失的问题可以通过外部正确使用避免掉的: 函数的调用必须显式通过实例来执行
`setTimeout(button.click, 3000) -> setTimeout(() => button.click(), 3000)`

2023-10-27 02:10 UTC, CptBreeza commented on src/api/jet/mod.ts
> +  return resolveResponse(body);
这个我看了一下，好像传不传是没有区别的呀

2023-10-27 02:10 UTC, CptBreeza commented on main.ts
> +import { default as adminCommand } from "@/subcommands/admin/mod.ts";
好的，我改一下

2023-10-27 02:10 UTC, CptBreeza commented on src/jcli/config/config.ts
> +  };
好的，我改一下

2023-10-27 02:59 UTC, vanppo commented on src/api/jet/mod.ts
> +  return resolveResponse(body);
应该是能通过两个函数的返回类型推断出来 但是显式的去声明会更好一些

2023-10-27 03:05 UTC, CptBreeza commented on src/api/jet/mod.ts
> +  return resolveResponse(body);
好，那我改一下

2023-10-27 05:20 UTC, CptBreeza commented
@fahchen 有空看一下这个

2023-10-27 05:21 UTC, moonRider approved these changes

2023-10-27 06:54 UTC, fahchen requested changes

2023-10-27 06:54 UTC, fahchen commented on src/jcli/config/json-serializer.ts
> +      return new Promise((resolve) => {
试试看 Promise.resolve

2023-10-27 06:54 UTC, fahchen commented on src/jcli/config/jcli-config-json.ts
> +  const homePath = Deno.env.get("HOME");
home_dir 的获取要不也放到 fs 类似的地方

2023-10-27 06:54 UTC, fahchen commented on src/jcli/config/config.ts
> +    this.#serializer = options?.serializer ?? makeJSONSerializer();
```suggestion
    this.#serializer = options?.serializer ?? makeJSONSerializer<T>();
```

2023-10-27 06:54 UTC, fahchen commented on src/jcli/config/config.ts
> +  #data: T | undefined = undefined;
undefined 还需要显式初始化吗？
@moonRider

2023-10-27 06:54 UTC, fahchen commented on src/subcommands/admin/projects/create/action.ts
> +    console.info("Provisioning local files...");
这个也走统一的 logger 呗

2023-10-27 06:59 UTC, moonRider commented on src/jcli/config/config.ts
> +  #data: T | undefined = undefined;
不用吧

2023-10-27 07:20 UTC, CptBreeza commented on src/subcommands/admin/projects/create/action.ts
> +    console.info("Provisioning local files...");
我这里感觉它们有点不一样？用 console.log 打印出来的是给用户看的、跟用户交互的输出，算是一种 UI（TUI）；用 logger.* 输出的是用来辅助使用（开发）的内部日志

2023-10-27 07:26 UTC, CptBreeza commented on src/jcli/config/jcli-config-json.ts
> +  const homePath = Deno.env.get("HOME");
目前使用到这个配置（`~/.config/jcli/config.json`）的有 2 个地方：
1. 在 `./main.ts` 里面使用 `logLevel` 来初始化 logger
2. 在 `@/src/api/jet/mod.ts` 里面使用 `jetEndpoint` 来发起向 jet 的网络请求
这 2 个都没有纳入测试的范围，要把 `homeDir` 放到 `api.fs` 里面的话，在测试环境里面就也得 mock 这个接口，但在测试环境里面完全没有用，所以我觉得目前可以不把它放到类似 fs 的地方去？

2023-10-27 07:39 UTC, vanppo approved these changes

2023-10-27 12:49 UTC, fahchen commented on src/subcommands/admin/projects/create/action.ts
> +    console.info("Provisioning local files...");
我把这两者合并了看的，我们需要分开看吗？

2023-10-27 12:54 UTC, fahchen commented on src/jcli/config/jcli-config-json.ts
> +  const homePath = Deno.env.get("HOME");
我想让核心代码对 deno 没有依赖，只依赖最少的 web api（列表详见 https://wintercg.org/work）

2023-10-27 12:57 UTC, fahchen commented on src/jcli/config/json-serializer.ts
> +      return new Promise((resolve) => {
这里也可以试试 Promise.resolve

2023-10-28 05:23 UTC, CptBreeza commented on src/jcli/config/jcli-config-json.ts
> +  const homePath = Deno.env.get("HOME");
行，我改一下

2023-10-28 05:32 UTC, CptBreeza commented on src/subcommands/admin/projects/create/action.ts
> +    console.info("Provisioning local files...");
我觉得是要的。后面我还计划引入有颜色的文字、进度条还有那种转圈的文字动画，这些感觉不好放到 log 里面去；还有就是 log 未来是可以使用文件 adapter 的。

2023-10-29 00:31 UTC, fahchen approved these changes

2023-10-31 05:15 UTC, merged