feat: enable instance
Byzanteam/jcli pull request #29
Opened 2024-03-03 15:29 UTC by danewalters

2024-03-04 05:30 UTC, CptBreeza commented on src/api/jet/queries/plugin-enable-instance.ts
> +      }
这里只请求 `id` 字段就可以了

2024-03-04 05:30 UTC, CptBreeza commented on src/subcommands/plugin/enable/mod.ts
> +  .option("-n, --name <instanceName:string>", "instance name")
这个我觉得做成一个 arg 不要做成 option 吧
cc @fahchen 你觉得呢

2024-03-04 05:30 UTC, CptBreeza commented on test/subcommands/plugin/enable/action_test.ts
再测一下 --prod option 吧

2024-03-04 06:32 UTC, fahchen commented on deno.lock
> +    ]
把 lockfile 删除了重新生成一下呢，我感觉这部分有点重复

2024-03-04 06:32 UTC, fahchen commented on src/subcommands/plugin/enable/mod.ts
> +  .description("Enadle plugins")
```suggestion
  .description("Enable a plugin")
```

2024-03-04 06:32 UTC, fahchen commented on src/subcommands/plugin/enable/mod.ts
> +  .option("-n, --name <instanceName:string>", "instance name")
同意

2024-03-04 09:01 UTC, fahchen commented on src/subcommands/plugin/enable/mod.ts
> +  .description("Enadle a plugin")
enable 单词打错了
```suggestion
  .description("Enable a plugin instance")
```

2024-03-04 09:04 UTC, fahchen requested changes

2024-03-04 09:04 UTC, fahchen commented on deno.lock
这个文件还是有问题，你本地的 deno 版本是多少 `deno --version`，升级到最新试试，你没有新增依赖，这个文件不应该被更新的

更新 lockfile 参考之前其他项目写的 task，你现在执行的命令不完整，应该要包含 check 和 test

2024-03-04 09:41 UTC, danewalters commented on deno.lock
<img width="359" alt="Screenshot 2024-03-04 at 17 40 38" src="https://github.com/Byzanteam/jcli/assets/91400014/4cb776e8-166c-4398-a183-26285aa31b8d">

我这边运行就会产生
``` json
 "workspace": {
    "dependencies": [
      "npm:@scure/base@1.1.3",
      "npm:ejs@3.1.9",
      "npm:jsonpatch@3.1.0",
      "npm:jsonschema@1.4.1",
      "npm:just-diff@6.0.2"
    ]
  }
```

2024-03-04 10:17 UTC, fahchen requested changes

2024-03-04 10:17 UTC, fahchen commented on deno.lock
> -    "https://deno.land/x/cliffy@v1.0.0-rc.3/ansi/colors.ts": "328916ea1627c202b39f2ed0f1ca65a573cfb75fa8986aa3dbcc0b7463911005",
对于 lock file 的改动不应该和其他 commits 混到一起

2024-03-04 10:17 UTC, fahchen commented on deno.lock
> -    "https://deno.land/x/cliffy@v1.0.0-rc.3/ansi/colors.ts": "328916ea1627c202b39f2ed0f1ca65a573cfb75fa8986aa3dbcc0b7463911005",
加一个 lockfile update 的 task 吧

2024-03-05 00:44 UTC, fahchen requested changes

2024-03-05 00:44 UTC, fahchen commented on deno.jsonc
> +    "lockfile:update": "deno cache --reload --lock=deno.lock --lock-write test/mod.ts && deno task check:types && deno task test"
```suggestion
    "lockfile:update": "deno cache --reload --lock=deno.lock --lock-write main.ts && deno task check:types && deno task test"
```

2024-03-05 00:45 UTC, fahchen commented on deno.lock
> -    "https://deno.land/x/cliffy@v1.0.0-rc.3/ansi/colors.ts": "328916ea1627c202b39f2ed0f1ca65a573cfb75fa8986aa3dbcc0b7463911005",
这一行应该不会被删除吧

2024-03-05 02:07 UTC, danewalters commented on deno.lock
> -    "https://deno.land/x/cliffy@v1.0.0-rc.3/ansi/colors.ts": "328916ea1627c202b39f2ed0f1ca65a573cfb75fa8986aa3dbcc0b7463911005",
我这边只要执行就会被删除，要不sf，你拉下来跑一下

2024-03-05 02:07 UTC, fahchen commented on deno.lock
> -    "https://deno.land/x/cliffy@v1.0.0-rc.3/ansi/colors.ts": "328916ea1627c202b39f2ed0f1ca65a573cfb75fa8986aa3dbcc0b7463911005",
我试试看

2024-03-05 02:41 UTC, fahchen approved these changes

2024-03-05 02:42 UTC, CptBreeza approved these changes

2024-03-05 02:53 UTC, merged