feat: add one line install
Byzanteam/jcli pull request #43
Opened 2024-04-10 08:00 UTC by YkeLit

- add install function
- create config file
- add uninstall script

2024-04-10 08:47 UTC, fahchen commented on install.sh
> +    fi
为什么要 sudo 呢？

2024-04-10 08:47 UTC, fahchen commented on install.sh
> +    mkdir ${FILE_JCLI_CONFIG_DIRECTORY}
如果文件目录存在也不报错呢
```suggession
    mkdir -p ${FILE_JCLI_CONFIG_DIRECTORY}
```

2024-04-10 08:50 UTC, fahchen commented on install.sh
> +    touch ${FILE_JCLI_CONFIG_DIRECTORY}/config.json
如果 config.json 不存在，创建一个，并给一个初始化的内容，内容我提一个 PR 给一下

2024-04-10 08:50 UTC, fahchen reviewed
在 README 里面给一下 install 命令，文件地址用这个吧 https://raw.githubusercontent.com/Byzanteam/jcli/main/main.ts

2024-04-10 09:15 UTC, fahchen commented on install.sh
> +    touch ${FILE_JCLI_CONFIG_DIRECTORY}/config.json
```json
{
  "$schema": "https://cdn.jsdelivr.net/gh/Byzanteam/jcli/schemas/jcli-config.json"
}
```

2024-04-10 09:15 UTC, fahchen commented on install.sh
> +    touch ${FILE_JCLI_CONFIG_DIRECTORY}/config.json
```json
{
  "$schema": "https://cdn.jsdelivr.net/gh/Byzanteam/jcli/schemas/jcli-config.json"
}
```

2024-04-10 09:16 UTC, fahchen commented on install.sh
> +trap remove_uninstall EXIT
uninstall 报错了
![image](https://github.com/Byzanteam/jcli/assets/855678/604b31b5-1988-40cb-a717-117015007a6d)

2024-04-11 07:38 UTC, fahchen requested changes

2024-04-11 07:38 UTC, fahchen commented on README.md
> +The install.sh script provides a convenient way to deploy jcli.
```suggestion
The install.sh script provides a convenient way to install jcli.
```

2024-04-11 07:38 UTC, fahchen commented on install.sh
权限有些问题
```bash
❯ curl -sfL https://raw.githubusercontent.com/Byzanteam/jcli/09ac5ef/install.sh | sh -                                                                                                                                                                                                                                                                           15:37:08
touch: /usr/local/bin/jcli-ro-test: Permission denied
[INFO]  Finding release for channel latest
[INFO]  Using v0.1.1 as release
[INFO]  Downloading binary https://github.com/Byzanteam/jcli/releases/download/v0.1.1/jcli-aarch64-apple-darwin
[INFO]  Installing jcli to /usr/local/bin/jcli
mv: rename /var/folders/vf/sqywbmmx7s98f5ys3zsw7chc0000gn/T/jcli-install.XXXXXXXXXX.BGVCT6MVgP/jcli to /usr/local/bin/jcli: Permission denied
```

2024-04-11 07:43 UTC, YkeLit commented on install.sh
你之前有没有安过哦，我在我电脑和公司那台华为服务器上跑过都没问题

2024-04-11 07:48 UTC, fahchen commented on install.sh
还是不行呢
```shell
❯ sudo rm /usr/local/bin/jcli                                                                                                                                                                                                                                                                                                                                    15:47:37
Password:
breeze 🌱 main [!?] via 🦀 v1.76.0
▶ sudo rm /usr/local/bin/jcli-uninstall.sh                                                                                                                                                                                                                                                                                                                       15:47:43
breeze 🌱 main [!?] via 🦀 v1.76.0
▶ curl -sfL https://raw.githubusercontent.com/Byzanteam/jcli/09ac5ef/install.sh | sh -                                                                                                                                                                                                                                                                           15:47:46
touch: /usr/local/bin/jcli-ro-test: Permission denied
[INFO]  Finding release for channel latest
[INFO]  Using v0.1.1 as release
[INFO]  Downloading binary https://github.com/Byzanteam/jcli/releases/download/v0.1.1/jcli-aarch64-apple-darwin
[INFO]  Installing jcli to /usr/local/bin/jcli
mv: rename /var/folders/vf/sqywbmmx7s98f5ys3zsw7chc0000gn/T/jcli-install.XXXXXXXXXX.n0kFGMA1wg/jcli to /usr/local/bin/jcli: Permission denied
```

2024-04-11 07:49 UTC, fahchen commented on install.sh
> +        if ! sh -c "touch ${BIN_DIR}/jcli-ro-test && rm -rf ${BIN_DIR}/jcli-ro-test"; then
touch 这一步有权限的问题

2024-04-11 12:12 UTC, fahchen commented on install.sh
> +    info "The installation is successful. Use the following command to load the environment variables 'source ~/.bashrc'!"
这个提示是什么意思呀，没看懂呢？

2024-04-11 12:12 UTC, fahchen commented on install.sh
> +sed -i 's|^export PATH=$PATH:$HOME/bin$||' $HOME/.bashrc
我觉得不应该去改变用户的配置，这样有点不好

2024-04-11 12:12 UTC, fahchen commented on install.sh
> +    fi
现在看起来，还是得这么做

2024-04-11 12:37 UTC, YkeLit commented on install.sh
> +    info "The installation is successful. Use the following command to load the environment variables 'source ~/.bashrc'!"
这样做的话需要手动去加载变量

2024-04-11 14:27 UTC, YkeLit commented on install.sh
> +sed -i 's|^export PATH=$PATH:$HOME/bin$||' $HOME/.bashrc
还是用 sudo ，把文件放到 /usr/local/bin 目录比较好

2024-04-12 01:56 UTC, CptBreeza approved these changes

2024-04-12 02:29 UTC, fahchen approved these changes, later dismissed

2024-04-12 02:32 UTC, fahchen requested changes

2024-04-12 02:32 UTC, fahchen commented on install.sh
> +  "$schema": "https://cdn.jsdelivr.net/gh/Byzanteam/jcli/schemas/jcli-config.json"
`$schema` 这个也被替换了，但是我们又没有这个变量，现在生成的内容如下
```json
{
  "": "https://cdn.jsdelivr.net/gh/Byzanteam/jcli/schemas/jcli-config.json"
}
```

2024-04-12 02:36 UTC, YkeLit commented on install.sh
> +  "$schema": "https://cdn.jsdelivr.net/gh/Byzanteam/jcli/schemas/jcli-config.json"
我改了

2024-04-12 02:45 UTC, fahchen approved these changes

2024-04-12 02:45 UTC, merged