feat: jcli projects list command
Byzanteam/jcli pull request #48
Opened 2024-04-24 10:35 UTC by danewalters

2024-04-24 12:11 UTC, fahchen requested changes

2024-04-24 12:11 UTC, fahchen commented on src/api/jet.ts
> +}
不需要新增这个吧，js 支持动态 args 的

2024-04-24 12:11 UTC, fahchen commented on test/subcommands/admin/projects/list/action_test.ts
> +//   import action from "@/subcommands/admin/var/list/action.ts";
```suggestion
```

2024-04-24 12:45 UTC, fahchen commented on src/subcommands/admin/projects/list/action.ts
> +  const tableData = [["name", "id"]];
```suggestion
  const tableData = [["Name", "ID"]];
```

2024-04-24 12:45 UTC, fahchen commented on src/subcommands/admin/projects/list/action.ts
> +  api.console.log(colors.bold.underline.blue(table.toString()));
不加这个颜色吧，我看着有点晃眼睛

<img width="479" alt="image" src="https://github.com/Byzanteam/jcli/assets/855678/cc4ef308-39fd-4a4f-bcf9-1d0cc583f11d">

```suggestion
  api.console.log(table.toString());
```

2024-04-24 13:14 UTC, danewalters commented on src/subcommands/admin/projects/list/action.ts
> +  api.console.log(colors.bold.underline.blue(table.toString()));
这么帅的颜色🤡

2024-04-25 06:47 UTC, fahchen requested changes

2024-04-25 06:47 UTC, fahchen commented on src/subcommands/admin/projects/list/action.ts
> -import { colors } from "cliffy-ansi-colors";
依赖也移除一下

2024-04-25 07:47 UTC, fahchen approved these changes

2024-04-25 13:21 UTC, merged