feat: jcli upgrade command
Byzanteam/jcli pull request #49
Opened 2024-04-29 09:33 UTC by danewalters

2024-04-29 09:54 UTC, fahchen commented on main.ts
> +const { version } = JSON.parse(await Deno.readTextFile("./deno.jsonc"));
这样看行不
https://v8.dev/features/import-assertions
https://github.com/tc39/proposal-import-attributes
```suggestion
import { version } from "./deno.jsonc" assert { type: 'json' };
```

2024-04-30 02:04 UTC, danewalters commented on main.ts
> +const { version } = JSON.parse(await Deno.readTextFile("./deno.jsonc"));
<img width="938" alt="Screenshot 2024-04-30 at 10 03 42" src="https://github.com/Byzanteam/jcli/assets/91400014/3fbe7b38-90c9-4a0a-afb4-4ede9307631d">

2024-04-30 02:05 UTC, danewalters commented on main.ts
> +const { version } = JSON.parse(await Deno.readTextFile("./deno.jsonc"));
感觉不太行，这个我昨天测试过了，只有 `deno.json` 可以 `deno.jsonc` 不行。

2024-04-30 02:13 UTC, fahchen commented on main.ts
> +const { version } = JSON.parse(await Deno.readTextFile("./deno.jsonc"));
你把 jsonc 改成 json 吧，反正我们也没用到 comment

2024-04-30 03:33 UTC, fahchen requested changes

2024-04-30 03:33 UTC, fahchen commented on main.ts
> +    destinationDir: "/usr/local/bin",
先查询一下 jcli 放在哪的，然后根据这个位置来设置

2024-04-30 03:33 UTC, fahchen commented on main.ts
> +      const exit_code = parseInt(`8${error.code}`);
这里前面加个 8 有什么含义吗？

2024-04-30 04:05 UTC, danewalters commented on main.ts
> +      const exit_code = parseInt(`8${error.code}`);
这个是我看到的他这么写的，然后查了一下资料
程序中使用具有特定前缀 "8" 的错误代码。这是一种组织错误代码的常见方法，可以快速的分辨不同错误类型

2024-04-30 06:29 UTC, fahchen requested changes

2024-04-30 06:29 UTC, fahchen commented on main.ts
> +import { version } from "./deno.json" with { type: "json" };
导入统一放到一起，放到上面

2024-04-30 06:29 UTC, fahchen commented on main.ts
> +    destinationDir: Deno.cwd(),
位置不对，应该是 jcli 的位置

2024-04-30 10:09 UTC, fahchen requested changes

2024-04-30 10:09 UTC, fahchen commented on src/subcommands/upgrade/mod.ts
> +const getExecutablePath = async (executableName: string) => {
```suggestion
const getDestinationDir = async (executableName: string) => {
```

2024-04-30 10:09 UTC, fahchen commented on src/subcommands/upgrade/mod.ts
> +}
这里用强制断言来解决类型问题

2024-05-01 00:53 UTC, fahchen approved these changes

2024-05-06 06:18 UTC, merged

2024-05-06 06:20 UTC, fahchen commented on deno.json
>      "sqlite": "https://deno.land/x/sqlite@v3.8/mod.ts",
单独开一个 PR 把依赖都换到 jsr 去吧