feat: push importmap
Byzanteam/jcli pull request #60
Opened 2024-06-12 10:03 UTC by danewalters

2024-06-13 01:33 UTC, fahchen requested changes

2024-06-13 01:33 UTC, fahchen commented on src/jcli/config/project-json.ts
> +    scopes: {},
如果没有设置就不传值到后端，保持为 nil 就好了，也就是说不给默认值

2024-06-13 07:42 UTC, danewalters commented on src/jcli/config/project-json.ts
> +    scopes: {},
没有值就是为空
<img width="712" alt="Screenshot 2024-06-13 at 15 39 56" src="https://github.com/Byzanteam/jcli/assets/91400014/f9998c24-f027-4da5-802f-e459138566d7">
这个操作的值是存数据库的，上传的值是用的 `config` 如果没有设置就是 `undefined`
<img width="597" alt="Screenshot 2024-06-13 at 15 42 01" src="https://github.com/Byzanteam/jcli/assets/91400014/d3fbfe0f-4505-428d-8ba8-87a58a39c286">

2024-06-13 09:36 UTC, fahchen requested changes

2024-06-13 09:36 UTC, fahchen commented on src/jcli/config/project-json.ts
> +    scopes: {},
你都检查一下改动的代码，所有涉及到 import map 的都不用给默认值，这里只是一处

2024-06-13 09:36 UTC, fahchen commented on src/jet/project.ts
> +  scopes: ProjectScopes;
```suggestion
  imports?: ProjectImports;
  scopes?: ProjectScopes;
```

2024-06-13 09:36 UTC, fahchen commented on test/subcommands/push/action/push-configuration_test.ts
> +        scopes: {},
没有设置过，就不给默认值

```suggestion
        imports: undefined,
        scopes: undefined
```

2024-06-13 09:36 UTC, fahchen commented on src/api/jet/mod.ts
> +    scopes: {},
不给默认值

2024-06-13 09:36 UTC, fahchen commented on test/subcommands/push/action/push-configuration_test.ts
成功的测试用例里面添加一个 imports 和 scopes 为 undefined 的测试用例

2024-06-13 09:36 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
imports 和 scopes 如果不符合格式要求，这个校验没有设计进来

2024-06-13 09:36 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +
将 imports 和 scopes 各看作一个整体，里面的部分不用做 diff 了

2024-06-13 09:36 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
新增的逻辑添加测试 `test/jcli/config/project-json-test.ts`

2024-06-14 03:19 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
格式校验用的是 schema 不符合要求就不会走到这一步

2024-06-14 03:22 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
这个测试加一下

2024-06-14 09:29 UTC, fahchen requested changes

2024-06-14 09:29 UTC, fahchen commented on src/api/jet/mod.ts
> +    scopes: undefined,
```suggestion
```

2024-06-14 09:29 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  patch.imports = value as ProjectImports;
1. value 确实存在再设置到 patch 上，补一个测试
2. 这个断言有问题，value 应该可以为 undefined

2024-06-14 09:29 UTC, fahchen commented on test/api/jet.ts
> +            scopes: undefined,
```suggestion
```

2024-06-14 09:29 UTC, fahchen commented on test/jcli/config/project-json-test.ts
> +      console.log("diff", diff);
认真点

2024-06-14 09:29 UTC, fahchen commented on test/jcli/config/project-json-test.ts
> +      assertNotEquals(diff, undefined);
这个是多余的，288L 那里保证了不是 undefined

2024-06-14 09:29 UTC, fahchen commented on test/jcli/config/project-json-test.ts
> +      const updatedImports = { "lib": "v2" };
添加测试用例
1. 从 undefined 变有值
2. 从有值变 undefined

2024-06-14 09:33 UTC, fahchen commented on test/subcommands/push/action/push-configuration_test.ts
> +      assertEquals(config.scopes, undefined);
这部分测试的是什么？

2024-06-14 09:34 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
> +  patch.imports = value as ProjectImports;
value 为undefined 的时候也是可以赋值的，就是将整个改为 undefined

2024-06-14 09:35 UTC, danewalters commented on test/subcommands/push/action/push-configuration_test.ts
> +      assertEquals(config.scopes, undefined);
测试的是 import_map 相关的 schema 没有通过校验

2024-06-14 12:33 UTC, fahchen approved these changes

2024-06-15 09:54 UTC, merged