fix: update config imports and scopes file error
Byzanteam/jcli pull request #65
Opened 2024-07-02 08:50 UTC by danewalters

2024-07-02 08:53 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
>  function buildImportsPatch(
看下怎么补个测试呢

2024-07-02 09:03 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
>  }
看下用这个 https://www.npmjs.com/package/just-diff-apply 能不能把 patch apply 一下，不手动处理这些 patch

2024-07-02 09:13 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
>  function buildImportsPatch(
https://github.com/Byzanteam/jcli/blob/d399a337a418222a1629be66dd4174ce64a7039b/test/jcli/config/project-json-test.ts#L277-L310
这里的测试用例拆小一点，把 add，remove，replace 都覆盖到

2024-07-02 09:48 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
>  }
可能不太行，他的处理逻辑有点不太适配我们的这个情况，我们会有多个子节点这种情况，他处理不了，可能得根据这个自己编写一下
<img width="879" alt="Screenshot 2024-07-02 at 17 47 39" src="https://github.com/Byzanteam/jcli/assets/91400014/5a52c5e7-0cd5-4ab6-a371-b34f580c4e84">

2024-07-02 09:51 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
>  }
你的参数没传对，patch 也给得不对
1. apply 的第二个参数传 array
2. 每个 patch 的 path 去掉第一个元素

2024-07-02 09:51 UTC, fahchen requested changes
https://github.com/Byzanteam/jcli/pull/65#discussion_r1662223975

2024-07-02 10:29 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
>  }
replace 的情况需要单独处理，因为我们的节点是为空的
<img width="990" alt="Screenshot 2024-07-02 at 18 29 02" src="https://github.com/Byzanteam/jcli/assets/91400014/7b691c67-ff9b-4cba-9aa1-8cc33f9642f9">

2024-07-02 12:47 UTC, fahchen requested changes

2024-07-02 12:47 UTC, fahchen commented on test/jcli/config/project-json-test.ts
这个文件名有问题，测试没有跑这个文件
-> `test/jcli/config/project-json_test.ts`

2024-07-02 12:47 UTC, fahchen commented on test/jcli/config/project-json-test.ts
> +      assertEquals(diffFour.scopes, initialScopes);
测试重新组织，每个测试只负责测试一个场景
通过 describe test 来组织

2024-07-02 12:47 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  patch.imports = context.dataWas.imports;
代码实现得有问题，看下下面这个测试用例能不能过
```ts
      {
        const initial = build({
          imports: {
            "@std/foo": "jsr:@std/foo@^1.2.3",
            "@std/bar": "jsr:@std/bar@^1.2.3",
          },
        });
        const updated = build({
          imports: {
            "@std/foo": "jsr:@std/foo@^2.0.0",
            "@std/baz": "jsr:@std/bar@^1.2.3",
          },
        });
        const diff = initial.diff(updated);
        console.log(diff);
      }
```

2024-07-02 13:00 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  patch.imports = context.dataWas.imports;
```suggestion
  if (!patch.imports) patch.imports = { ...context.dataWas.imports };

  diffApply(patch, [
    { op, path: ["imports", ...context.restPathNodes] as string[], value },
  ]);

  if (patch.imports && Object.keys(patch.imports).length === 0) {
    patch.imports = undefined;
  }
```

2024-07-03 07:22 UTC, danewalters commented on test/jcli/config/project-json_test.ts
> +          action: "create",
这个正确的就是小写，在其他测试文件中也是小写，但是这个测试文件好像重来没运行过，所以一直没改，改一下名字就可以运行了

2024-07-03 07:31 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  if (!patch.scopes) patch.scopes = { ...context.dataWas.scopes };
解构只对 object 第一层有用，scopes 是嵌套的 object 这里有问题，还是会改到 dataWas 上的数据

2024-07-03 07:31 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +        assertObjectMatch(resultDiff!, { imports: definedImports });
这里用 equals 来判断

2024-07-03 07:31 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +        const definedImports = { "lib": "v2" };
这个有点太假了，找一个真实一点的例子

2024-07-03 07:31 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +        assertEquals(resultDiff.imports, additionalImports);
这里的这些变量反而降低了可读性
```typescript
        const initialConfig = build({});
        const updatedConfig = build({ imports: { "lib": "v2", "src": "./src" } });
        const diff = initialConfig.diff(updatedConfig);

        assertEquals(diff.imports, { "lib": "v2", "src": "./src" });
        // 顺便断言一下 config 没有被修改到
        assertEquals(initialConfig.imports, undefined);
        assertEquals(diff.imports, updatedConfig.imports);
```

2024-07-03 07:32 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +        assertEquals(resultDiff.imports, additionalImports);
看下 context.dataWas 能不能做成 Readonly 的来避免我们对它进行修改

2024-07-03 07:35 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +      });
测试覆盖度还不够，特别是更新的情况

2024-07-03 07:35 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +          action: "create",
嗯，可以的

2024-07-04 03:51 UTC, fahchen requested changes

2024-07-04 03:51 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  patch.scopes = contextScopes;
这个还是会改到 dataWas 上的值

2024-07-04 03:51 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  }
判断还是不要在这里做，因为后面的 op 进来的时候如果这里被设置为了 undefined，会导致 381L 获取到旧的值

2024-07-04 03:51 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  patch.scopes = contextScopes;
还是会改到 dataWas 上的值

用 https://developer.mozilla.org/en-US/docs/Web/API/structuredClone 来复制

2024-07-04 03:51 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +        assertEquals(initialConfig.toJSON().imports, initialImports);
测试用例全部改成下面这种，不要用变量了，全部用 literal objects，因为这些变量有可能被修改，这种情况下这里面的一些断言就没有意义（比如 `assertEquals(initialConfig.toJSON().imports, initialImports);`)
```typescript
        const initialConfig = build({
          imports: {
            "#utils": "./utils"
          }
        });
        const updatedConfig = build({
          imports: {
            "#utils": "./utils",
            "#functions": "./functions",
            "src": "./src",
          },
        });
        const diff = initialConfig.diff(updatedConfig);

        assertEquals(diff.imports, {
          ...
        });
        assertEquals(initialConfig.toJSON().imports, { ... });
```

2024-07-04 03:54 UTC, fahchen commented on test/jcli/config/project-json_test.ts
> +        };
到官方文档里面找点例子，或者 GitHub 上找点实际的例子来写测试

https://github.com/WICG/import-maps?tab=readme-ov-file#scoping-examples

2024-07-04 08:20 UTC, fahchen commented on src/api/jet/mod.ts
> +    : JSON.stringify(command.scopes);
做一个 function 出来吧

2024-07-04 08:20 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  }
这个是不是没必要判断？像上面一样给默认值就好了

2024-07-04 08:20 UTC, fahchen commented on test/jcli/config/project-json_test.ts
imports 和 scopes 都各补一个复杂的测试（现在的这些测试比较小，但使用的时候经常是多种操作同时出现），这个测试包含 add, remove, update 操作。特别地对于 scopes 考虑它的 scope 里面的 object 的 add remove update 操作

2024-07-05 03:30 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
> +  }
这个许哟啊判断一下，这个有多层嵌套的情况，如果是只修改某一个小值也会被指定为 replace

2024-07-05 03:48 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +  }
给一下有问题的测试用例，我跑下

2024-07-05 07:19 UTC, fahchen approved these changes

2024-07-05 07:24 UTC, merged