wip
Byzanteam/jcli pull request #66
Opened 2024-08-01 08:27 UTC by danewalters

2024-08-09 09:39 UTC, fahchen requested changes

2024-08-09 09:39 UTC, fahchen commented on test/subcommands/push/action/push-configuration_test.ts
测试用例缺失
1. items 及顺序都没有变化
2. 仅 items 的顺序发生变化

2024-08-09 09:39 UTC, fahchen commented on test/subcommands/push/action/push-configuration_test.ts
capability 没有测试到，目前看起来 capability 和 instance 的逻辑应该一样，这里想办法把实现逻辑合并成一个，这样测试就不用都写一遍了

2024-08-09 10:17 UTC, danewalters commented on test/subcommands/push/action/push-configuration_test.ts
> capability 没有测试到，目前看起来 capability 和 instance 的逻辑应该一样，这里想办法把实现逻辑合并成一个，这样测试就不用都写一遍了

okk，我优化一下

2024-08-10 17:30 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
> +            ...value as ProjectPluginInstance,
@fahchen  感觉这样写不太好，但是类型我调整的有问题，sf，你看看有没有什么好的办法呢

2024-08-12 10:47 UTC, fahchen approved these changes

2024-08-13 02:14 UTC, merged