feat: function inspect all
Byzanteam/jcli pull request #68
Opened 2024-09-10 14:57 UTC by danewalters

2024-09-11 09:41 UTC, fahchen requested changes

2024-09-11 09:41 UTC, fahchen commented on src/subcommands/function/inspect/action.ts
> +    "MEMORY_LIMIT_EXCEEDED": colors.red,
```suggestion
    "UNSPECIFIED": colors.gray,
    "BOOTING": colors.cyan,
    "RUNNING": colors.green,
    "BOOT_FAILED": colors.red,
    "DESTROYED": colors.magenta,
    "EARLY_EXITED": colors.red,
    "UNCAUGHT_EXCEPTION": colors.red,
    "MEMORY_LIMIT_EXCEEDED": colors.red,
```

2024-09-11 09:41 UTC, fahchen commented on src/subcommands/function/inspect/action.ts
> +        return buildDeploymentTable(deployment!, name, environmentName);
这里的 `deployment!` 的断言有问题，如果 deployment 不存在，这里也会断言存在

2024-09-11 09:41 UTC, fahchen commented on test/subcommands/function/inspect/action_test.ts
> +  });
原来的测试应该不用改也能通过才对

2024-09-11 09:44 UTC, danewalters commented on test/subcommands/function/inspect/action_test.ts
> +  });
我给所有的都加上了颜色，就是指定了某一个状态也会有颜色
<img width="792" alt="Screenshot 2024-09-11 at 17 43 48" src="https://github.com/user-attachments/assets/7df9b548-78c3-4084-a918-15cec7ee0918">

2024-09-11 10:48 UTC, fahchen requested changes

2024-09-11 10:48 UTC, fahchen commented on src/subcommands/function/inspect/action.ts
> +    return Table.from([]);
不要返回空 Table，通过其他方式处理这种情况

2024-09-11 10:48 UTC, fahchen commented on test/subcommands/function/inspect/action_test.ts
> +  });
改动的就只应该有颜色这部分才对，其他的改动的原因是什么

2024-09-12 02:00 UTC, fahchen requested changes

2024-09-12 02:00 UTC, fahchen commented on src/subcommands/function/inspect/action.ts
> +  };
常量放到 function 外面

2024-09-12 02:00 UTC, fahchen commented on src/subcommands/function/inspect/action.ts
> +  }
```suggestion
): Promise<string | undefined> {
  const deployment = await api.jet.inspectFunction({
    projectId,
    environmentName,
    functionName,
  });

  if (!deployment) {
    api.console.log(`Function ${functionName} not found.`);
    return;
  }
```

2024-09-12 02:00 UTC, fahchen commented on src/subcommands/function/inspect/action.ts
> +      ).sort();
通过 sql 过滤和排序

2024-09-12 02:00 UTC, fahchen commented on test/subcommands/function/inspect/action_test.ts
> +    await api.fs.mkdir("functions/my_func");
```suggestion
    await api.fs.mkdir("functions/main");
    await api.fs.mkdir("functions/api");
    await api.fs.mkdir("functions/_core");
```

2024-09-12 03:24 UTC, fahchen approved these changes

2024-09-12 03:27 UTC, merged