fix: upload config argument error
Byzanteam/jcli pull request #69
Opened 2024-09-30 06:03 UTC by danewalters

2024-10-08 06:56 UTC, fahchen requested changes
查一下 GraphQL，我发现另外的几个 command （包括 `projects_draft_configuration_instance_command_input` 和 `projects_draft_configuration_capability_command_input`）也有些不对

2024-10-08 06:56 UTC, fahchen commented on src/jcli/config/project-json-patch-builder.ts
> +      }
这里的判断根据 instance 和 capability 来区分一下，不要用 `"pluginName" in obj`

2024-10-17 06:25 UTC, fahchen requested changes
https://github.com/Byzanteam/jcli/pull/69#discussion_r1791299389

2024-10-17 06:33 UTC, vanppo commented
这个任务是要做什么呀 哪里的参数有什么问题呢

2024-10-17 06:36 UTC, danewalters commented
> 这个任务是要做什么呀 哪里的参数有什么问题呢

instance 的 update 接口有问题，多传了一个 pluginName，参数里面没这个所以得去掉
<img width="283" alt="Screenshot 2024-10-17 at 14 35 52" src="https://github.com/user-attachments/assets/bea164d5-c72b-474f-b099-53559234416d">

2024-10-17 06:52 UTC, vanppo approved these changes

2024-10-17 07:02 UTC, danewalters commented on src/jcli/config/project-json-patch-builder.ts
> +      }
改了使用的是 instance 进行的判断

2024-10-17 07:03 UTC, fahchen approved these changes

2024-10-17 07:09 UTC, merged